name: gmt
channels:
  - pytorch
  - conda-forge
  - nvidia
  - anaconda
  - defaults
dependencies:
  - requests=2.26.0=pyhd3eb1b0_0
  - tqdm=4.62.1=pyhd3eb1b0_1
  - nltk=3.6.2=pyhd3eb1b0_0
  - pandas=1.3.2=py37h8c16a72_0
  - pytorch=1.9.0=py3.7_cuda11.1_cudnn8.0.5_0
  - scikit-learn=0.24.2=py37ha9443f7_0
  - glob2=0.7=pyhd3eb1b0_0
  - networkx=2.6.2=pyhd3eb1b0_0
  - pyodbc=4.0.31=py37h295c915_0
  - pip
  - pip:
    - sparqlwrapper==1.8.5
    - urllib3==1.25.11
    - transformers==4.18.0
    - numpy==1.21.5
    - faiss-gpu==1.7.2
